{{- define "receiveramplifier.deployment.container" -}}
image: "{{ include "common.image.registry" (dict "image" .Values.image "context" .) }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
imagePullPolicy: {{ .Values.image.pullPolicy }}
env:
ports:
- containerPort: 9000
  name: app
- containerPort: 9404
  name: metrics
- containerPort: 1618
  name: health
livenessProbe:
  tcpSocket:
    port: app
readinessProbe:
  tcpSocket:
    port: app
volumeMounts:
  - name: stackstate-amplifier-application-config
    mountPath: /opt/docker/etc/application.conf
    subPath: application.conf
{{- end -}}

{{- define "receiveramplifier.deployment" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "receiveramplifier.deployment.container" .) -}}
{{- $receiveramplifierContainer := (merge $overrideContainer $commonContainer) }}
spec:
  template:
    metadata:
      annotations:
        {{- include "common.metrics.annotations" (dict "metrics" .Values.metrics "port" "9404" "container_name" "receiveramplifier") | indent 8 }}
    spec:
      {{- include "common.image.pullSecret.name" (dict "images" (list .Values.image) "context" $) | nindent 6 }}
      containers:
      - {{ toYaml $receiveramplifierContainer | nindent 8 }}
      volumes:
      - name: stackstate-amplifier-application-config
        configMap:
          name: {{ template "common.fullname.short" . }}
{{- end -}}

{{- $commonDeployment := fromYaml (include "common.deployment" .) -}}
{{- $receiveramplifierDeployment := fromYaml (include "receiveramplifier.deployment" .) -}}
{{- toYaml (merge $receiveramplifierDeployment $commonDeployment) -}}
