apiVersion: v1
description: Official Elastic helm chart for Elasticsearch
home: https://github.com/elastic/helm-charts
name: elasticsearch
version: 7.6.2-stackstate.12
appVersion: 7.6.2
sources:
  - https://github.com/elastic/elasticsearch
icon: https://helm.elastic.co/icons/elasticsearch.png
maintainers:
  - name: Jeroen van Erp
    email: jvanerp@stackstate.com
  - name: Remco Beckers
    email: rbeckers@stackstate.com
  - name: Vincent Partington
    email: vpartington@stackstate.com
