{{- define "stackstate.sync.configmap" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-sync
data:
  application_stackstate.conf: |
    {{- if .Values.stackstate.components.sync.config }}
    {{- .Values.stackstate.components.sync.config | nindent 4 -}}
    {{- end }}
    {{- end -}}

    {{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
    {{- $stackstateSyncConfigMap := fromYaml (include "stackstate.sync.configmap" .) -}}
    {{- toYaml (merge $stackstateSyncConfigMap $commonConfigMap) -}}
