{{- define "stackstate.slicing.configmap" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-slicing
data:
  application_stackstate.conf: |
    {{- if .Values.stackstate.components.slicing.config }}
    {{- .Values.stackstate.components.slicing.config | nindent 4 -}}
    {{- end }}
    {{- end -}}

    {{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
    {{- $stackstateSlicingConfigMap := fromYaml (include "stackstate.slicing.configmap" .) -}}
    {{- toYaml (merge $stackstateSlicingConfigMap $commonConfigMap) -}}
