{{- define "stackstate.router.configmap" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-router
data:
  envoy-config: |-
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8080
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
              codec_type: auto
              stat_prefix: ingress_http
              upgrade_configs:
              - upgrade_type: websocket
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/admin/"
                    route:
                      cluster: "{{ template "common.fullname.short" . }}-server-admin"
                      prefix_rewrite: "/"
                  - match:
                      prefix: "/api"
                    route:
                      cluster: "{{ template "common.fullname.short" . }}-server-main"
                  - match:
                      prefix: "/loginCallback"
                    route:
                      cluster: "{{ template "common.fullname.short" . }}-server-main"
                  - match:
                      prefix: "/loginInfo"
                    route:
                      cluster: "{{ template "common.fullname.short" . }}-server-main"
                  - match:
                      prefix: "/logout"
                    route:
                      cluster: "{{ template "common.fullname.short" . }}-server-main"
                  - match:
                      prefix: "/stsAgent"
                    route:
                      cluster: "{{ template "common.fullname.short" . }}-receiver"
                  - match:
                      prefix: "/receiver/"
                    route:
                      cluster: "{{ template "common.fullname.short" . }}-receiver"
                      prefix_rewrite: "/"
                  - match:
                      prefix: "/"
                    route:
                      cluster: "{{ template "common.fullname.short" . }}-ui"
              http_filters:
              - name: envoy.router
                typed_config: {}
      clusters:
      - name: "{{ template "common.fullname.short" . }}-server-main"
        type: STRICT_DNS
        lb_policy: LEAST_REQUEST
        http_protocol_options: {}
        connect_timeout: 2s
        hosts:
        - socket_address:
            address: "{{ template "common.fullname.short" . }}-server"
            port_value: 7070
      - name: "{{ template "common.fullname.short" . }}-server-admin"
        type: STRICT_DNS
        lb_policy: LEAST_REQUEST
        http_protocol_options: {}
        connect_timeout: 2s
        hosts:
        - socket_address:
            address: "{{ template "common.fullname.short" . }}-server"
            port_value: 7071
      - name: "{{ template "common.fullname.short" . }}-receiver"
        type: STRICT_DNS
        lb_policy: LEAST_REQUEST
        http_protocol_options: {}
        connect_timeout: 2s
        hosts:
        - socket_address:
            address: "{{ template "common.fullname.short" . }}-receiver"
            port_value: 7077
      - name: "{{ template "common.fullname.short" . }}-ui"
        type: STRICT_DNS
        lb_policy: LEAST_REQUEST
        http_protocol_options: {}
        connect_timeout: 2s
        hosts:
        - socket_address:
            address: "{{ template "common.fullname.short" . }}-ui"
            port_value: 8080

    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001

{{- end -}}

{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateServerConfigMap := fromYaml (include "stackstate.router.configmap" .) -}}
{{- toYaml (merge $stackstateServerConfigMap $commonConfigMap) -}}
