{{- define "stackstate.server.configmap" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-server
data:
  application_stackstate.conf: |
{{- if .Values.stackstate.components.server.config }}
{{- .Values.stackstate.components.server.config | nindent 4 -}}
{{- end }}
{{- if .Values.caspr.enabled }}
    stackstate {
      tenantAware = true
      tenant {
        identifier = {{ .Values.caspr.subscription.tenant }}
        name = "{{ .Values.caspr.subscription.tenantobj.name }}"
        subscription {
{{- if .Values.caspr.subscription.expirationDate }}
          expirationDate = {{ .Values.caspr.subscription.expirationDate }}
{{- end }}
          plan = {{ .Values.caspr.subscription.planobj.name }}
        }
      }
    }
{{- end }}
{{- end -}}


{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateServerConfigMap := fromYaml (include "stackstate.server.configmap" .) -}}
{{- toYaml (merge $stackstateServerConfigMap $commonConfigMap) -}}
