{{- define "stackstate.api.deployment.container.init" -}}
name: server-init
command:
- sh
- -c
- |
  /entrypoint -c {{ include "stackstate.kafka.endpoint" . }},{{ include "stackstate.zookeeper.endpoint" . }},{{ .Release.Name }}-hbase-hdfs-nn:9000,{{ .Release.Name }}-initializer:7071 -t 300
image: "{{include "stackstate.wait.image.registry" .}}/{{ .Values.stackstate.components.wait.image.repository }}:{{ .Values.stackstate.components.wait.image.tag }}"
imagePullPolicy: Always
{{- end -}}

{{- define "stackstate.api.deployment.container.main" -}}
args:
- -startRole
- api
env:
{{- include "stackstate.common.envvars" . }}
{{- include "stackstate.api.envvars" . }}
- name: API_KEY
  valueFrom:
    secretKeyRef:
      name: {{ template "common.fullname.short" . }}-receiver
      key: sts-receiver-api-key
- name: ELASTICSEARCH_URI
  value: "http://{{ include "stackstate.es.endpoint" . }}"
- name: KAFKA_BROKERS
  value: {{ include "stackstate.kafka.endpoint" . | quote }}
- name: LICENSE_KEY
  valueFrom:
    secretKeyRef:
      name: {{ template "common.fullname.short" . }}-license
      key: sts-license-key
- name: RECEIVER_BASE_URL
  value: {{ printf "%s/%s" .Values.stackstate.receiver.baseUrl "receiver" | quote }}
- name: ZOOKEEPER_QUORUM
  value: {{ include "stackstate.zookeeper.endpoint" . | quote }}
- name: CONFIG_FORCE_stackstate_stackPacks_localStackPacksUri
  value: "hdfs://{{ .Release.Name }}-hbase-hdfs-nn:9000/stackpacks"
{{- if .Values.stackstate.admin.authentication.enabled }}
- name: CONFIG_FORCE_stackstate_adminApi_authentication_enabled
  value: "true"
{{- end }}
image: "{{ include "stackstate.image.registry" . }}/{{ .Values.stackstate.components.api.image.repository }}{{ .Values.stackstate.components.all.image.repositorySuffix }}:{{ default .Values.stackstate.components.all.image.tag .Values.stackstate.components.api.image.tag }}"
imagePullPolicy: {{ default .Values.stackstate.components.all.image.pullPolicy .Values.stackstate.components.api.image.pullPolicy | quote }}
livenessProbe:
  httpGet:
    path: /liveness
    port: health
  initialDelaySeconds: 60
  timeoutSeconds: 5
name: api
ports:
- containerPort: 1618
  name: health
- containerPort: 7070
  name: api
- containerPort: 7071
  name: admin
{{- if .Values.stackstate.components.all.metrics.enabled }}
- containerPort: 9404
  name: metrics
{{- end }}
readinessProbe:
  httpGet:
    path: /readiness
    port: health
  initialDelaySeconds: 60
  timeoutSeconds: 5
{{- with .Values.stackstate.components.api.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
securityContext:
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534
volumeMounts:
- name: config-volume
  mountPath: /opt/docker/etc/application_stackstate.conf
  subPath: application_stackstate.conf
{{- end -}}

{{- define "stackstate.api.deployment" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "stackstate.api.deployment.container.main" .) -}}
{{- $stsStackstateApiMainContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideContainer := fromYaml (include "stackstate.api.deployment.container.init" .) -}}
{{- $stsStackstateApiInitContainer := (merge $overrideContainer $commonContainer) -}}
metadata:
  name: {{ template "common.fullname.short" . }}-api
  labels:
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.stackstate.components.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: api
  template:
    metadata:
      annotations:
        {{- include "stackstate.common.secret.checksum" . | nindent 8 }}
        {{- include "stackstate.license.secret.checksum" . | nindent 8 }}
        {{- include "stackstate.api.secret.checksum" . | nindent 8 }}
        {{- include "stackstate.server.configmap.checksum" . | nindent 8 }}
      labels:
        app.kubernetes.io/component: api
    spec:
    {{- if .Values.stackstate.components.all.image.pullSecretName }}
      imagePullSecrets:
      - name: '{{ .Values.stackstate.components.all.image.pullSecretName }}'
    {{- else if .Values.stackstate.components.all.image.pullSecretDockerConfigJson }}
      imagePullSecrets:
      - name: '{{ template "common.fullname.short" . }}-pull-secret'
    {{- end }}
      initContainers:
      - {{ toYaml $stsStackstateApiInitContainer | nindent 8 }}
      containers:
      - {{ toYaml $stsStackstateApiMainContainer | nindent 8 }}
    {{- if or .Values.stackstate.components.all.nodeSelector .Values.stackstate.components.api.nodeSelector }}
      nodeSelector:
      {{- with .Values.stackstate.components.all.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.api.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.affinity .Values.stackstate.components.api.affinity }}
      affinity:
      {{- with .Values.stackstate.components.all.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.api.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.tolerations .Values.stackstate.components.api.tolerations }}
      tolerations:
      {{- with .Values.stackstate.components.all.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.api.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "common.fullname.short" . }}-api
{{- end -}}

{{- if .Values.stackstate.server.split }}
{{- $commonDeployment := fromYaml (include "common.deployment" .) -}}
{{- $apiDeployment := fromYaml (include "stackstate.api.deployment" .) -}}
{{- toYaml (merge $apiDeployment $commonDeployment) -}}
{{- end}}
