{{- define "stackstate.k2es.deployment.stsEventsToEs.container" -}}
args:
- -Dlogback.configurationFile=/opt/docker/etc_log/logback.groovy
- sts-events
name: sts2es
volumeMounts:
- name: config-volume-log
  mountPath: /opt/docker/etc_log
{{- end -}}

{{- define "stackstate.k2es.stsEventsToEs.deployment" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $commonKafkaToEsContainer := fromYaml (include "stackstate.k2es.deployment.common.container" .) -}}
{{- $commonKafkaToEsInitContainer := fromYaml (include "stackstate.k2es.deployment.common.initcontainer" .) -}}
{{- $stsEventsToEsContainer := fromYaml (include "stackstate.k2es.deployment.stsEventsToEs.container" .) }}

metadata:
  name: {{ template "common.fullname.short" . }}-sts2es
  labels:
    app.kubernetes.io/component: sts2es
spec:
  replicas: {{ .Values.stackstate.components.k2es.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: sts2es
  template:
    metadata:
      annotations:
        {{- include "common.metrics.annotations" (dict "metrics" .Values.stackstate.components.all.metrics "port" "9404" "container_name" "sts2es") | indent 8 }}
        {{- include "stackstate.common.secret.checksum" . | nindent 8 }}
        {{- include "stackstate.k2es.secret.checksum" . | nindent 8 }}
      labels:
        app.kubernetes.io/component: sts2es
    spec:
      {{ include "stackstate.image.pullSecret.name" . | nindent 6 }}
      initContainers:
      - {{ toYaml (merge $commonKafkaToEsInitContainer $commonContainer) | nindent 8 }}
      containers:
      - {{ toYaml (merge $stsEventsToEsContainer $commonKafkaToEsContainer $commonContainer) | nindent 8 }}
      volumes:
        - name: config-volume-log
          configMap:
            name: {{ template "common.fullname.short" . }}-k2es-log
    {{- if or .Values.stackstate.components.all.nodeSelector .Values.stackstate.components.k2es.nodeSelector }}
      nodeSelector:
      {{- with .Values.stackstate.components.all.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.k2es.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.affinity .Values.stackstate.components.k2es.affinity }}
      affinity:
      {{- with .Values.stackstate.components.all.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.k2es.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.tolerations .Values.stackstate.components.k2es.tolerations }}
      tolerations:
      {{- with .Values.stackstate.components.all.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.k2es.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end -}}

{{- $commonDeployment := fromYaml (include "common.deployment" .) -}}
{{- $k2esStsEventsToEsDeployment := fromYaml (include "stackstate.k2es.stsEventsToEs.deployment" .) -}}
{{- toYaml (merge $k2esStsEventsToEsDeployment $commonDeployment) -}}
