{{- if and .Values.backup.enabled (or .Values.backup.stackGraph.restore.enabled .Values.backup.stackGraph.scheduled.enabled .Values.backup.elasticsearch.restore.enabled .Values.backup.elasticsearch.scheduled.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "common.fullname.short" . }}-backup-init-{{ now | date "20060102t150405" }}
  labels:
    app.kubernetes.io/component: backup
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backup
    spec:
      initContainers:
        - name: wait
          command:
            - sh
            - -c
            - |
              /entrypoint -c {{ include "stackstate.es.endpoint" . }},{{ include "stackstate.minio.endpoint" . }} -t 300
          image: "{{include "stackstate.wait.image.registry" .}}/{{ .Values.stackstate.components.wait.image.repository }}:{{ .Values.stackstate.components.wait.image.tag }}"
          imagePullPolicy: {{ .Values.stackstate.components.wait.image.pullPolicy | quote }}
      containers:
        - name: configure
          image: "{{include "stackstate.containerTools.image.registry" .}}/{{ .Values.stackstate.components.containerTools.image.repository }}:{{ .Values.stackstate.components.containerTools.image.tag }}"
          imagePullPolicy: {{ .Values.stackstate.components.containerTools.image.pullPolicy | quote }}
          command:
            - '/backup-restore-scripts/configure-backup.sh'
          env:
            {{- include "stackstate.backup.envvars" . | nindent 12 }}
          volumeMounts:
            {{- include "stackstate.backup.volumeMounts" . | nindent 16 }}
            - name: tmp-data
              mountPath: /tmp-data
      volumes:
        {{- include "stackstate.backup.volumes" . | nindent 8 }}
        - name: tmp-data
          persistentVolumeClaim:
            claimName: {{ template "common.fullname.short" . }}-backup-stackgraph-tmp-data
      restartPolicy: Never
{{- end }}
