{{- if .Values.stackstate.components.all.image.pullSecretUsername }}
  {{- $registryAuthDocument := dict -}}
  {{- $_ := set $registryAuthDocument "username" .Values.stackstate.components.all.image.pullSecretUsername }}
  {{- $_ := set $registryAuthDocument "password" .Values.stackstate.components.all.image.pullSecretPassword }}
  {{- $authMessage := printf "%s:%s" $registryAuthDocument.username $registryAuthDocument.password | b64enc }}
  {{- $_ := set $registryAuthDocument "auth" $authMessage }}
  {{- $registryAuthMap := dict .Values.stackstate.components.all.image.registry $registryAuthDocument }}
  {{- $dockerAuthsDocuments := dict "auths" $registryAuthMap }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.fullname.short" . }}-pull-secret
data:
  .dockerconfigjson: {{ $dockerAuthsDocuments | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}
