---
{{- if .Values.maxUnavailable }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "elasticsearch.uname" . }}-pdb"
  labels:
    {{- include "elasticsearch.labels.standard" . | nindent 4 }}
    {{- include "elasticsearch.labels.common" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.nodeGroup }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      app: "{{ template "elasticsearch.uname" . }}"
{{- end }}
