{{- define "elasticsearch.pull.secret" -}}
  {{- $fullName := include "elasticsearch.uname" .context -}}
  {{- $registryAuthDocument := dict -}}
  {{- $_ := set $registryAuthDocument "username" .username }}
  {{- $_ := set $registryAuthDocument "password" .password }}
  {{- $authMessage := printf "%s:%s" $registryAuthDocument.username $registryAuthDocument.password | b64enc }}
  {{- $_ := set $registryAuthDocument "auth" $authMessage }}
  {{- $registryAuthMap := dict .registry $registryAuthDocument }}
  {{- $dockerAuthsDocuments := dict "auths" $registryAuthMap }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-pull-secret
data:
  .dockerconfigjson: {{ $dockerAuthsDocuments | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}

{{- if.Values.pullSecretUsername }}
  {{ template "elasticsearch.pull.secret" (dict "username" .Values.pullSecretUsername "password" .Values.pullSecretPassword "registry" (include "elasticsearch.imageRegistry" $) "context" $) }}
{{- else if .Values.global }}
  {{- if .Values.global.imagePullUsername }}
    {{ template "elasticsearch.pull.secret" (dict "username" .Values.global.imagePullUsername "password" .Values.global.imagePullPassword "registry" (include "elasticsearch.imageRegistry" $) "context" $) }}
  {{- end }}
{{- end }}
