{{- define "distributed.k2es.deployment.multiMetricsToEs.container" -}}
args:
- multi-metrics
name: mm2es
{{- end -}}

{{- define "distributed.k2es.multiMetricsToEs.deployment" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $commonKafkaToEsContainer := fromYaml (include "distributed.k2es.deployment.common.container" .) -}}
{{- $commonKafkaToEsInitContainer := fromYaml (include "distributed.k2es.deployment.common.initcontainer" .) -}}
{{- $multiMetricsToEsContainer := fromYaml (include "distributed.k2es.deployment.multiMetricsToEs.container" .) }}

metadata:
  name: {{ template "common.fullname" . }}-mm2es
  labels:
    app.kubernetes.io/component: mm2es
spec:
  replicas: {{ .Values.stackstate.components.k2es.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: mm2es
  template:
    metadata:
      annotations:
        {{- include "distributed.common.secret.checksum" . | nindent 8 }}
        {{- include "distributed.k2es.secret.checksum" . | nindent 8 }}
      labels:
        app.kubernetes.io/component: mm2es
    spec:
    {{- if .Values.stackstate.components.all.image.pullSecret }}
      imagePullSecrets:
      - name: '{{ .Values.stackstate.components.all.image.pullSecret }}'
    {{- end }}
      initContainers:
      - {{ toYaml (merge $commonKafkaToEsInitContainer $commonContainer) | nindent 8 }}
      containers:
      - {{ toYaml (merge $multiMetricsToEsContainer $commonKafkaToEsContainer $commonContainer) | nindent 8 }}
    {{- if or .Values.stackstate.components.all.nodeSelector .Values.stackstate.components.k2es.nodeSelector }}
      nodeSelector:
      {{- with .Values.stackstate.components.all.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.k2es.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.affinity .Values.stackstate.components.k2es.affinity }}
      affinity:
      {{- with .Values.stackstate.components.all.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.k2es.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.tolerations .Values.stackstate.components.k2es.tolerations }}
      tolerations:
      {{- with .Values.stackstate.components.all.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.k2es.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end -}}

{{- $commonDeployment := fromYaml (include "common.deployment" .) -}}
{{- $k2esMultiMetricsToEsDeployment := fromYaml (include "distributed.k2es.multiMetricsToEs.deployment" .) -}}
{{- toYaml (merge $k2esMultiMetricsToEsDeployment $commonDeployment) -}}
