{{- define "distributed.server.deployment.container.init" -}}
name: server-init
command:
- sh
- -c
- |
  /entrypoint -c {{ include "distributed.es.endpoint" . }},{{ include "distributed.kafka.endpoint" . }},{{ include "distributed.zookeeper.endpoint" . }},{{ .Release.Name }}-hbase-hdfs-nn:9000 -t 300
image: "docker.io/dokkupaas/wait:latest"
imagePullPolicy: Always
{{- end -}}

{{- define "distributed.server.deployment.container.main" -}}
args:
- -start
env:
{{- include "distributed.common.envvars" . }}
{{- include "distributed.server.envvars" . }}
- name: API_KEY
  valueFrom:
    secretKeyRef:
      name: {{ template "common.fullname" . }}-receiver
      key: sts-receiver-api-key
- name: ELASTICSEARCH_URI
  value: "http://{{ include "distributed.es.endpoint" . }}"
- name: KAFKA_BROKERS
  value: {{ include "distributed.kafka.endpoint" . | quote }}
- name: LICENSE_KEY
  valueFrom:
    secretKeyRef:
      name: {{ template "common.fullname" . }}-server
      key: sts-license-key
- name: RECEIVER_BASE_URL
  value: {{ .Values.stackstate.receiver.baseUrl | quote }}
- name: ZOOKEEPER_QUORUM
  value: {{ include "distributed.zookeeper.endpoint" . | quote }}
- name: CONFIG_FORCE_stackstate_stackPacks_localStackPacksUri
  value: "hdfs://{{ .Release.Name }}-hbase-hdfs-nn:9000/stackpacks"
image: "{{ .Values.stackstate.components.server.image.repository }}:{{ default .Values.stackstate.components.all.image.tag .Values.stackstate.components.server.image.tag }}"
imagePullPolicy: {{ default .Values.stackstate.components.all.image.pullPolicy .Values.stackstate.components.server.image.pullPolicy | quote }}
livenessProbe:
  httpGet:
    path: /liveness
    port: admin
  initialDelaySeconds: 120
  timeoutSeconds: 5
name: server
ports:
- containerPort: 7070
  name: api
- containerPort: 7071
  name: admin
{{- if .Values.stackstate.components.all.metrics.enabled }}
- containerPort: 9404
  name: metrics
{{- end }}
readinessProbe:
  httpGet:
    path: /api/server/readiness
    port: api
  initialDelaySeconds: 120
  timeoutSeconds: 5
{{- with .Values.stackstate.components.server.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
securityContext:
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534
{{- end -}}

{{- define "distributed.server.deployment" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "distributed.server.deployment.container.main" .) -}}
{{- $stsDistributedServerMainContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideContainer := fromYaml (include "distributed.server.deployment.container.init" .) -}}
{{- $stsDistributedServerInitContainer := (merge $overrideContainer $commonContainer) -}}
metadata:
  name: {{ template "common.fullname" . }}-server
  labels:
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.stackstate.components.server.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: server
  template:
    metadata:
      annotations:
        {{- include "distributed.common.secret.checksum" . | nindent 8 }}
        {{- include "distributed.server.secret.checksum" . | nindent 8 }}
      labels:
        app.kubernetes.io/component: server
    spec:
      initContainers:
      - {{ toYaml $stsDistributedServerInitContainer | nindent 8 }}
      containers:
      - {{ toYaml $stsDistributedServerMainContainer | nindent 8 }}
    {{- if or .Values.stackstate.components.all.nodeSelector .Values.stackstate.components.server.nodeSelector }}
      nodeSelector:
      {{- with .Values.stackstate.components.all.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.server.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.affinity .Values.stackstate.components.server.affinity }}
      affinity:
      {{- with .Values.stackstate.components.all.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.server.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.tolerations .Values.stackstate.components.server.tolerations }}
      tolerations:
      {{- with .Values.stackstate.components.all.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.server.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end -}}

{{- $commonDeployment := fromYaml (include "common.deployment" .) -}}
{{- $serverDeployment := fromYaml (include "distributed.server.deployment" .) -}}
{{- toYaml (merge $serverDeployment $commonDeployment) -}}
