{{- define "distributed.k2es.deployment.multiMetricsToEs.container" -}}
args:
- /opt/docker/bin/kafka-multi-metrics-to-elasticsearch-app
name: mm2es
{{- end -}}

{{- define "distributed.k2es.multiMetricsToEs.deployment" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $commonKafkaToEsContainer := fromYaml (include "distributed.k2es.deployment.common.container" .) -}}
{{- $multiMetricsToEsContainer := fromYaml (include "distributed.k2es.deployment.multiMetricsToEs.container" .) }}

metadata:
  name: {{ template "common.fullname" . }}-mm2es
  labels:
    app.kubernetes.io/component: mm2es
spec:
  replicas: {{ .Values.stackstate.components.k2es.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: mm2es
  template:
    metadata:
      annotations:
        {{- include "distributed.common.secret.checksum" . | nindent 8 }}
        {{- include "distributed.k2es.secret.checksum" . | nindent 8 }}
      labels:
        app.kubernetes.io/component: mm2es
    spec:
      containers:
      - {{ toYaml (merge $multiMetricsToEsContainer $commonKafkaToEsContainer $commonContainer) | nindent 8 }}
      nodeSelector:
    {{- with .Values.stackstate.components.all.nodeSelector }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.stackstate.components.k2es.nodeSelector }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      affinity:
    {{- with .Values.stackstate.components.all.affinity }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.stackstate.components.k2es.affinity }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      tolerations:
    {{- with .Values.stackstate.components.all.tolerations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.stackstate.components.k2es.tolerations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}

{{- $commonDeployment := fromYaml (include "common.deployment" .) -}}
{{- $k2esMultiMetricsToEsDeployment := fromYaml (include "distributed.k2es.multiMetricsToEs.deployment" .) -}}
{{- toYaml (merge $k2esMultiMetricsToEsDeployment $commonDeployment) -}}
