{{- define "distributed.receiver.deployment.container.init" -}}
name: receiver-init
command:
- sh
- -c
- |
  /entrypoint -c {{ include "distributed.kafka.endpoint" . }} -t 300
image: "docker.io/dokkupaas/wait:latest"
imagePullPolicy: Always
{{- end -}}

{{- define "distributed.receiver.deployment.container.main" -}}
env:
{{- include "distributed.common.envvars" . }}
{{- include "distributed.receiver.envvars" . }}
- name: KAFKA_BROKERS
  value: {{ include "distributed.kafka.endpoint" . | quote }}
- name: API_KEY
  valueFrom:
    secretKeyRef:
      name: {{ template "common.fullname" . }}-receiver
      key: sts-receiver-api-key
image: "{{ .Values.stackstate.components.receiver.image.repository }}:{{ default .Values.stackstate.components.all.image.tag .Values.stackstate.components.receiver.image.tag }}"
imagePullPolicy: {{ default .Values.stackstate.components.all.image.pullPolicy .Values.stackstate.components.receiver.image.pullPolicy | quote }}
name: receiver
ports:
- containerPort: 1618
  name: health
- containerPort: 7077
  name: receiver
{{- if .Values.stackstate.components.all.metrics.enabled }}
- containerPort: 9404
  name: metrics
{{- end }}
livenessProbe:
  httpGet:
    path: /liveness
    port: health
  initialDelaySeconds: 30
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /readiness
    port: health
  initialDelaySeconds: 30
  timeoutSeconds: 5
{{- with .Values.stackstate.components.receiver.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
securityContext:
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534
{{- end -}}

{{- define "distributed.receiver.deployment" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "distributed.receiver.deployment.container.main" .) -}}
{{- $stsDistributedReceiverMainContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideContainer := fromYaml (include "distributed.receiver.deployment.container.init" .) -}}
{{- $stsDistributedReceiverInitContainer := (merge $overrideContainer $commonContainer) -}}
metadata:
  name: {{ template "common.fullname" . }}-receiver
  labels:
    app.kubernetes.io/component: receiver
spec:
  replicas: {{ .Values.stackstate.components.receiver.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: receiver
  template:
    metadata:
      annotations:
        {{- include "distributed.common.secret.checksum" . | nindent 8 }}
        {{- include "distributed.receiver.secret.checksum" . | nindent 8 }}
      labels:
        app.kubernetes.io/component: receiver
    spec:
      initContainers:
      - {{ toYaml $stsDistributedReceiverInitContainer | nindent 8 }}
      containers:
      - {{ toYaml $stsDistributedReceiverMainContainer | nindent 8 }}
    {{- if or .Values.stackstate.components.all.nodeSelector .Values.stackstate.components.receiver.nodeSelector }}
      nodeSelector:
      {{- with .Values.stackstate.components.all.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.receiver.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.affinity .Values.stackstate.components.receiver.affinity }}
      affinity:
      {{- with .Values.stackstate.components.all.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.receiver.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.tolerations .Values.stackstate.components.receiver.tolerations }}
      tolerations:
      {{- with .Values.stackstate.components.all.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.receiver.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end -}}

{{- $commonDeployment := fromYaml (include "common.deployment" .) -}}
{{- $receiverDeployment := fromYaml (include "distributed.receiver.deployment" .) -}}
{{- toYaml (merge $receiverDeployment $commonDeployment) -}}
