{{- if .Values.ingress.enabled -}}
{{- $fullName := include "common.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}-server
              servicePort: 7071
            path: /admin/?(.*)
          - backend:
              serviceName: {{ $fullName }}-server
              servicePort: 7070
            path: /?(api/.*)
          - backend:
              serviceName: {{ $fullName }}-server
              servicePort: 7070
            path: /?(loginCallback)
          - backend:
              serviceName: {{ $fullName }}-server
              servicePort: 7070
            path: /?(loginInfo)
          - backend:
              serviceName: {{ $fullName }}-server
              servicePort: 7070
            path: /?(logout)
          - backend:
              serviceName: {{ $fullName }}-receiver
              servicePort: 7077
            path: /receiver/?(.*)
          - backend:
              serviceName: {{ $fullName }}-ui
              servicePort: 8080
            path: /?(.*)
    {{- end }}
  {{- end }}
{{- end }}
