apiVersion: v1
appVersion: 2.0.6
version: 0.1.3
description: Helm chart for the StackState cluster agent.
keywords:
- aiops
- monitoring
- stackstate
home: https://github.com/StackVista/stackstate-agent
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
- name: sc250024
  email: scrooks@stackstate.com
name: cluster-agent
