#####################
# General variables #
#####################

global:
  extraEnv:
    # global.extraEnv.open -- Extra open environment variables to inject into pods.
    open: {}
    # global.extraEnv.secret -- Extra secret environment variables to inject into pods via a `Secret` object.
    secret: {}
  # global.imagePullSecrets -- Secrets / credentials needed for container image registry.
  imagePullSecrets: []

dependencies:
  kubeStateMetrics:
    # dependencies.kubeStateMetrics.enabled -- Whether or not to install the `kube-state-metrics` Deployment along with the StackState cluster agent. Set to `false` if you have `kube-state-metrics` already installed on the cluster.
    enabled: true

# nameOverride -- Override the name of the chart.
nameOverride: ""
# fullnameOverride -- Override the fullname of the chart.
fullnameOverride: ""

all:
  image:
    # all.image.registry -- The image registry to use.
    registry: "quay.io"


agent:
  containerRuntime:
    cri:
      # agent.containerRuntime.cri.enabled -- Enable / disable the configuration of CRI container check.
      enabled: false
    containerd:
      # agent.containerRuntime.containerd.enabled -- Enable / disable the configuration of containerd container check.
      enabled: false
  scc:
    # agent.scc.enabled -- Enable / disable the installation of the SecurityContextConfiguration needed for installation on OpenShift.
    enabled: false
  apm:
    # agent.apm.enabled -- Enable / disable the agent APM module.
    enabled: true
  networkTracing:
    # agent.networkTracing.enabled -- Enable / disable the agent network tracing module.
    enabled: true
  protocolInspection:
    # agent.protocolInspection.enabled -- Enable / disable the agent protocol inspection.
    enabled: true
  processAgent:
    # agent.processAgent.enabled -- Enable / disable the agent process agent module.
    enabled: true
  # agent.skipSslValidation -- Set to true if self signed certificates are used.
  skipSslValidation: false

  # agent.checksTagCardinality -- low, orchestrator or high. Orchestrator level adds pod_name, high adds display_container_name
  checksTagCardinality: orchestrator

  # agent.config --
  config:
    # agent.config.override -- A list of objects containing three keys `name`, `path` and `data`, specifying filenames at specific paths which need to be (potentially) overridden using a mounted configmap
    override: []

  image:
    # agent.image.repository -- Base container image repository.
    repository: stackstate/stackstate-agent-2
    # agent.image.tag -- Default container image tag.
    tag: 2.15.0
    # agent.image.pullPolicy -- Default container image pull policy.
    pullPolicy: IfNotPresent

  livenessProbe:
    # agent.livenessProbe.enabled -- Enable use of livenessProbe check.
    enabled: true
    # agent.livenessProbe.failureThreshold -- `failureThreshold` for the liveness probe.
    failureThreshold: 3
    # agent.livenessProbe.initialDelaySeconds -- `initialDelaySeconds` for the liveness probe.
    initialDelaySeconds: 15
    # agent.livenessProbe.periodSeconds -- `periodSeconds` for the liveness probe.
    periodSeconds: 15
    # agent.livenessProbe.successThreshold -- `successThreshold` for the liveness probe.
    successThreshold: 1
    # agent.livenessProbe.timeoutSeconds -- `timeoutSeconds` for the liveness probe.
    timeoutSeconds: 5

  # agent.logLevel -- Logging level for agent processes.
  logLevel: INFO

  # agent.priorityClassName -- Priority class for agent pods.
  priorityClassName: ""

  readinessProbe:
    # agent.readinessProbe.enabled -- Enable use of readinessProbe check.
    enabled: true
    # agent.readinessProbe.failureThreshold -- `failureThreshold` for the readiness probe.
    failureThreshold: 3
    # agent.readinessProbe.initialDelaySeconds -- `initialDelaySeconds` for the readiness probe.
    initialDelaySeconds: 15
    # agent.readinessProbe.periodSeconds -- `periodSeconds` for the readiness probe.
    periodSeconds: 15
    # agent.readinessProbe.successThreshold -- `successThreshold` for the readiness probe.
    successThreshold: 1
    # agent.readinessProbe.timeoutSeconds -- `timeoutSeconds` for the readiness probe.
    timeoutSeconds: 5

  resources:
    limits:
      # agent.resources.limits.cpu -- CPU resource limits.
      cpu: "400m"
      # agent.resources.limits.cpu -- Memory resource limits.
      memory: "1024Mi"
    requests:
      # agent.resources.requests.cpu -- CPU resource requests.
      cpu: "100m"
      # agent.resources.requests.cpu -- Memory resource requests.
      memory: "256Mi"

  # agent.updateStrategy -- The update strategy for the DaemonSet object.
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100

  # agent.nodeSelector -- Node labels for pod assignment.
  nodeSelector: {}

  # agent.tolerations -- Toleration labels for pod assignment.
  tolerations: []

  # agent.affinity -- Affinity settings for pod assignment.
  affinity: {}

clusterAgent:
  collection:
    # clusterAgent.collection.kubernetesEvents -- Enable / disable the cluster agent events collection.
    kubernetesEvents: true
    # clusterAgent.collection.kubernetesMetrics -- Enable / disable the cluster agent metrics collection.
    kubernetesMetrics: true
    # clusterAgent.collection.kubernetesTimeout -- Default timeout (in seconds) when obtaining information from the Kubernetes API.
    kubernetesTimeout: 10
    # clusterAgent.collection.kubernetesTopology -- Enable / disable the cluster agent topology collection.
    kubernetesTopology: true

  # clusterAgent.config --
  config:
    configMap:
      # clusterAgent.config.configMap.maxDataSize -- Maximum amount of characters for the data property of a ConfigMap collected by the kubernetes topology check
      maxDataSize: null
    # clusterAgent.config.override -- A list of objects containing three keys `name`, `path` and `data`, specifying filenames at specific paths which need to be (potentially) overridden using a mounted configmap
    override: []


  # clusterAgent.enabled -- Enable / disable the cluster agent.
  enabled: true

  image:
    # clusterAgent.image.repository -- Base container image repository.
    repository: stackstate/stackstate-cluster-agent
    # clusterAgent.image.tag -- Default container image tag.
    tag: 2.15.0
    # clusterAgent.image.pullPolicy -- Default container image pull policy.
    pullPolicy: IfNotPresent

  livenessProbe:
    # clusterAgent.livenessProbe.enabled -- Enable use of livenessProbe check.
    enabled: true
    # clusterAgent.livenessProbe.failureThreshold -- `failureThreshold` for the liveness probe.
    failureThreshold: 3
    # clusterAgent.livenessProbe.initialDelaySeconds -- `initialDelaySeconds` for the liveness probe.
    initialDelaySeconds: 15
    # clusterAgent.livenessProbe.periodSeconds -- `periodSeconds` for the liveness probe.
    periodSeconds: 15
    # clusterAgent.livenessProbe.successThreshold -- `successThreshold` for the liveness probe.
    successThreshold: 1
    # clusterAgent.livenessProbe.timeoutSeconds -- `timeoutSeconds` for the liveness probe.
    timeoutSeconds: 5

  # clusterAgent.logLevel -- Logging level for cluster-agent processes.
  logLevel: INFO

  # clusterAgent.priorityClassName -- Priority class for cluster-agent pods.
  priorityClassName: ""

  readinessProbe:
    # clusterAgent.readinessProbe.enabled -- Enable use of readinessProbe check.
    enabled: true
    # clusterAgent.readinessProbe.failureThreshold -- `failureThreshold` for the readiness probe.
    failureThreshold: 3
    # clusterAgent.readinessProbe.initialDelaySeconds -- `initialDelaySeconds` for the readiness probe.
    initialDelaySeconds: 15
    # clusterAgent.readinessProbe.periodSeconds -- `periodSeconds` for the readiness probe.
    periodSeconds: 15
    # clusterAgent.readinessProbe.successThreshold -- `successThreshold` for the readiness probe.
    successThreshold: 1
    # clusterAgent.readinessProbe.timeoutSeconds -- `timeoutSeconds` for the readiness probe.
    timeoutSeconds: 5

  # clusterAgent.replicaCount -- Number of replicas of the cluster agent to deploy.
  replicaCount: 1

  # clusterAgent.strategy -- The strategy for the Deployment object.
  strategy:
    type: RollingUpdate
    # rollingUpdate:
    #   maxUnavailable: 1

  resources:
    limits:
      # clusterAgent.resources.limits.cpu -- CPU resource limits.
      cpu: "200m"
      # clusterAgent.resources.limits.memory -- Memory resource limits.
      memory: "256Mi"
    requests:
      # clusterAgent.resources.requests.cpu -- CPU resource requests.
      cpu: "50m"
      # clusterAgent.resources.requests.memory -- Memory resource requests.
      memory: "64Mi"

  # clusterAgent.nodeSelector -- Node labels for pod assignment.
  nodeSelector: {}

  # clusterAgent.tolerations -- Toleration labels for pod assignment.
  tolerations: []

  # clusterAgent.affinity -- Affinity settings for pod assignment.
  affinity: {}

clusterChecks:
  # clusterChecks.enabled -- Enable / disable runnning cluster checks in a separately deployed pod
  enabled: true
  scc:
    # clusterChecks.scc.enabled -- Enable / disable the installation of the SecurityContextConfiguration needed for installation on OpenShift
    enabled: false
  apm:
    # clusterChecks.apm.enabled -- Enable / disable the agent APM module.
    enabled: true
  networkTracing:
    # clusterChecks.networkTracing.enabled -- Enable / disable the agent network tracing module.
    enabled: true
  processAgent:
    # clusterChecks.processAgent.enabled -- Enable / disable the agent process agent module.
    enabled: true
  # clusterChecks.skipSslValidation -- Set to true if self signed certificates are used.
  skipSslValidation: false

  # agent.checksTagCardinality -- low, orchestrator or high. Orchestrator level adds pod_name, high adds display_container_name
  checksTagCardinality: orchestrator

  # clusterChecks.config --
  config:
    # clusterChecks.config.override -- A list of objects containing three keys `name`, `path` and `data`, specifying filenames at specific paths which need to be (potentially) overridden using a mounted configmap
    override: []

  image:
    # clusterChecks.image.repository -- Base container image repository.
    repository: stackstate/stackstate-agent-2
    # clusterChecks.image.tag -- Default container image tag.
    tag: 2.15.0
    # clusterChecks.image.pullPolicy -- Default container image pull policy.
    pullPolicy: IfNotPresent

  livenessProbe:
    # clusterChecks.livenessProbe.enabled -- Enable use of livenessProbe check.
    enabled: true
    # clusterChecks.livenessProbe.failureThreshold -- `failureThreshold` for the liveness probe.
    failureThreshold: 3
    # clusterChecks.livenessProbe.initialDelaySeconds -- `initialDelaySeconds` for the liveness probe.
    initialDelaySeconds: 15
    # clusterChecks.livenessProbe.periodSeconds -- `periodSeconds` for the liveness probe.
    periodSeconds: 15
    # clusterChecks.livenessProbe.successThreshold -- `successThreshold` for the liveness probe.
    successThreshold: 1
    # clusterChecks.livenessProbe.timeoutSeconds -- `timeoutSeconds` for the liveness probe.
    timeoutSeconds: 5

  # clusterChecks.logLevel -- Logging level for clusterchecks agent processes.
  logLevel: INFO

  # clusterChecks.priorityClassName -- Priority class for clusterchecks agent pods.
  priorityClassName: ""

  readinessProbe:
    # clusterChecks.readinessProbe.enabled -- Enable use of readinessProbe check.
    enabled: true
    # clusterChecks.readinessProbe.failureThreshold -- `failureThreshold` for the readiness probe.
    failureThreshold: 3
    # clusterChecks.readinessProbe.initialDelaySeconds -- `initialDelaySeconds` for the readiness probe.
    initialDelaySeconds: 15
    # clusterChecks.readinessProbe.periodSeconds -- `periodSeconds` for the readiness probe.
    periodSeconds: 15
    # clusterChecks.readinessProbe.successThreshold -- `successThreshold` for the readiness probe.
    successThreshold: 1
    # clusterChecks.readinessProbe.timeoutSeconds -- `timeoutSeconds` for the readiness probe.
    timeoutSeconds: 5

  # clusterChecks.replicas -- Number of clusterchecks agent pods to schedule
  replicas: 1

  resources:
    limits:
      # clusterChecks.resources.limits.cpu -- CPU resource limits.
      cpu: "400m"
      # clusterChecks.resources.limits.cpu -- Memory resource limits.
      memory: "1024Mi"
    requests:
      # clusterChecks.resources.requests.cpu -- CPU resource requests.
      cpu: "100m"
      # clusterChecks.resources.requests.cpu -- Memory resource requests.
      memory: "256Mi"

  # clusterChecks.strategy -- The strategy for the Deployment object.
  strategy:
    type: RollingUpdate
    # rollingUpdate:
    #   maxUnavailable: 1

  # clusterChecks.nodeSelector -- Node labels for pod assignment.
  nodeSelector: {}

  # clusterChecks.tolerations -- Toleration labels for pod assignment.
  tolerations: []

  # clusterChecks.affinity -- Affinity settings for pod assignment.
  affinity: {}

  kubeStateMetrics:
    # clusterChecks.kubeStateMetrics.url -- URL of the KubeStateMetrics server. This needs to be configured if the KubeStateMetrics server is not enabled by default in this Helm chart.
    url: ""

########################
# StackState variables #
########################

stackstate:
  # stackstate.apiKey -- (string) **PROVIDE YOUR API KEY HERE** API key to be used by the StackState agent.
  apiKey:
  cluster:
    # stackstate.cluster.name -- (string) **PROVIDE KUBERNETES CLUSTER NAME HERE** Name of the Kubernetes cluster where the agent will be installed.
    name:
    # stackstate.cluster.authToken -- Provide a token to enable secure communication between the agent and the cluster agent.
    authToken: ""
  # stackstate.url -- (string) **PROVIDE STACKSTATE URL HERE** URL of the StackState installation to receive data from the agent.
  url:
