---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fullname.short" . }}
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fullname.short" . }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fullname.short" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "fullname.short" . }}
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fullname.short" . }}
rules:
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["get", "list", "watch"]
  {{- with .Values.rbac }}
    {{- range $groupedObject := . }}
- apiGroups:
  - "{{ $groupedObject.apiGroup }}"
  resources:
    {{- toYaml $groupedObject.objects | nindent 4 }}
  verbs: ["*"]
    {{- end }}
  {{- end }}
