dependencies:
- name: common
  repository: https://helm.stackstate.io
  version: 0.3.1
- name: elasticsearch
  condition: elasticsearch.enabled
  repository: https://helm.elastic.co
  version: 7.5.2
- name: hbase
  condition: hbase.enabled
  repository: https://helm.stackstate.io
  version: 0.1.21
- name: kafka
  condition: kafka.enabled
  repository: https://charts.bitnami.com/bitnami
  version: 7.1.3
- name: zookeeper
  version: 5.3.4
  repository: https://charts.bitnami.com/bitnami
  condition: zookeeper.enabled
