dependencies:
- name: common
  repository: file://../common
  version: 0.1.8
- name: elasticsearch
  condition: elasticsearch.enabled
  repository: https://helm.elastic.co
  version: 7.4.1
- name: hbase
  condition: hbase.enabled
  repository: file://../hbase
  version: 0.1.12
- name: kafka
  condition: kafka.enabled
  repository: https://charts.bitnami.com
  version: 7.0.3
- name: zookeeper
  version: 5.1.1
  repository: https://charts.bitnami.com
  condition: zookeeper.enabled
