dependencies:
- name: common
  repository: https://helm.stackstate.io
  version: 0.1.8
- name: elasticsearch
  condition: elasticsearch.enabled
  repository: https://helm.elastic.co
  version: 7.5.2
- name: hbase
  condition: hbase.enabled
  repository: https://helm.stackstate.io
  version: 0.1.16
- name: kafka
  condition: kafka.enabled
  repository: https://charts.bitnami.com
  version: 7.1.3
- name: zookeeper
  version: 5.3.4
  repository: https://charts.bitnami.com
  condition: zookeeper.enabled
