#####################
# General variables #
#####################


aws:
  # aws.configFile -- The AWS config file contents.
  configFile: |-
    [default]
  # aws.credentialsFile -- The AWS credentials file contents.
  credentialsFile: |-
    [default]
  # aws.mountPath -- The mount path of the AWS config and credentials file.
  mountPath: /home/stackstate/.aws

# backoffLimit -- For failed jobs, how many times to retry.
backoffLimit: 3
# failedJobsHistoryLimit -- The number of failed CronJob executions that are saved.
failedJobsHistoryLimit: 5
# successfulJobsHistoryLimit -- The number of successful CronJob executions that are saved.
successfulJobsHistoryLimit: 5
# restartPolicy -- For failed jobs, how to handle restarts.
restartPolicy: OnFailure
# schedule -- Default schedule for this CronJob.
schedule: "*/10 * * * *"

# podAnnotations -- Annotations for the `Job` pod.
podAnnotations: {}

image:
  # image.repository -- Base container image registry.
  repository: stackstate/python-amicleaner
  # image.tag -- Default container image tag.
  tag: latest
  # image.pullPolicy -- Default container image pull policy.
  pullPolicy: Always

# imagePullSecrets -- Extra secrets / credentials needed for container image registry.
imagePullSecrets: []
# nameOverride -- Override the name of the chart.
nameOverride: ""
# fullnameOverride -- Override the fullname of the chart.
fullnameOverride: ""

resources:
  limits:
    # resources.limits.cpu -- CPU resource limits.
    cpu: "100m"
    # resources.limits.memory -- Memory resource limits.
    memory: "128Mi"
  requests:
    # resources.requests.cpu -- CPU resource requests.
    cpu: "100m"
    # resources.requests.memory -- Memory resource requests.
    memory: "128Mi"

# nodeSelector -- Node labels for pod assignment.
nodeSelector: {}

# tolerations -- Toleration labels for pod assignment.
tolerations: []

# affinity -- Affinity settings for pod assignment.
affinity: {}
