ingress:
  enabled: true
  hosts:
  - host: some-receiveramplifier.website.com
    paths:
      - /
      - /another-path
  tls:
  - secretName: some-tls-secret
    hosts:
      - some-receiveramplifier.website.com

receiveramplifier:
  targetUrl: "http://localhost"
  image:
    pullSecretUsername:
