image:
  # image.registry -- Registry containing the image for the Kommoner operator
  registry: quay.io
  # image.repository -- Repository containing the image for the Kommoner operator
  repository: stackstate/petros-d-kubelet-stats-exporter
  # image.tag -- Tag of the image for the Kommoner operator
  tag: 0.9.2
  # image.pullPolicy -- Pull policy for the image for the Kommoner operator
  pullPolicy: IfNotPresent
# nodeSelector:
#   node.kubernetes.io/purpose-core: "yes"
resources:
  limits:
    cpu: 50m
    memory: 250Mi
  requests:
    cpu: 10m
    memory: 50Mi
serviceMonitor:
  # serviceMonitor.enabled -- Enables ServiceMonitor resource for prometheus-operator
  enabled: true
  # serviceMonitor.internal -- Scrape interval for the ServiceMonitor
  interval: 300s
  # serviceMonitor.scrapeTimeout -- Scrape timeout for the ServiceMonitor
  scrapeTimeout: 120s
dashboards:
  # dashboards.enabled -- Enables Dashboard resource for prometheus-operator
  enabled: true
