#####################
# General variables #
#####################

# backoffLimit -- For failed jobs, how many times to retry.
backoffLimit: 3
# failedJobsHistoryLimit -- The number of failed CronJob executions that are saved.
failedJobsHistoryLimit: 5
# successfulJobsHistoryLimit -- The number of successful CronJob executions that are saved.
successfulJobsHistoryLimit: 5
# restartPolicy -- For failed jobs, how to handle restarts.
restartPolicy: OnFailure
# schedule -- Default schedule for this CronJob.
schedule: "0 */4 * * *"

extraEnv:
  # extraEnv.open -- Extra open environment variables to inject into pods.
  open: {}
  # extraEnv.secret -- Extra secret environment variables to inject into pods via a `Secret` object.
  secret: {}

image:
  # image.repository -- Base container image registry.
  repository: quay.io/stackstate/iceman
  # image.tag -- Default container image tag.
  tag: master
  # image.pullPolicy -- Default container image pull policy.
  pullPolicy: Always

# podAnnotations -- Annotations to inject into `Job` pods.
podAnnotations: {}

# imagePullSecrets -- Extra secrets / credentials needed for container image registry.
imagePullSecrets: []
# nameOverride -- Override the name of the chart.
nameOverride: ""
# fullnameOverride -- Override the fullname of the chart.
fullnameOverride: ""

rbac:
  # rbac.serviceAccountAnnotations -- Additional `ServiceAccount` annotations.
  serviceAccountAnnotations: {}

resources:
  limits:
    # resources.limits.cpu -- CPU resource limits.
    cpu: "100m"
    # resources.limits.memory -- Memory resource limits.
    memory: "128Mi"
  requests:
    # resources.requests.cpu -- CPU resource requests.
    cpu: "100m"
    # resources.requests.memory -- Memory resource requests.
    memory: "128Mi"

# nodeSelector -- Node labels for pod assignment.
nodeSelector: {}

# tolerations -- Toleration labels for pod assignment.
tolerations: []

# affinity -- Affinity settings for pod assignment.
affinity: {}

####################
# Iceman variables #
####################

iceman:
  # iceman.awsRegion -- Default AWS region where the S3 bucket resides.
  awsRegion: eu-west-1
  # iceman.logLevel -- Log level of the Iceman application.
  logLevel: info
  # iceman.s3Bucket -- (string) **REQUIRED** S3 bucket name to place the backup configuration.
  s3Bucket:
  # iceman.stackstatePassword -- (string) **REQUIRED** Administrator password for the Admin API running on all StackStates.
  stackstatePassword:
  # iceman.stackstateUsername -- (string) **REQUIRED** Administrator username for the Admin API running on all StackStates.
  stackstateUsername:
