concurrencyPolicy: Forbid
failedJobsHistoryLimit: 5
schedule: "*/10 * * * *"
successfulJobsHistoryLimit: 5

image:
  # image.repository -- Base container image registry.
  repository: quay.io/rebuy/aws-nuke
  # image.tag -- Default container image tag.
  tag: v2.14.0
  # image.pullPolicy -- Default container image pull policy.
  pullPolicy: Always

awsNuke:
  # awsNuke.config -- (string) **REQUIRED** AWS Nuke configuration file that will be used with the `--config` flag.
  config:
  # awsNuke.extraArgs -- Extra command-line options to pass.
  extraArgs: {}
  # awsNuke.noDryRun -- If specified, it actually deletes found resources. Otherwise it just lists all candidates.
  noDryRun: false
  # awsNuke.profile -- Name of the AWS profile name for accessing the AWS API. Cannot be used together with `--access-key-id` and `--secret-access-key`.
  profile: ""
  # awsNuke.quiet -- Don't show filtered resources.
  quiet: false
  # awsNuke.verbose -- Enables debug output.
  verbose: false
