apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackstate-standalone.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-standalone.labels" . | indent 4 }}
type: Opaque
data:
  sts-license-key: {{ .Values.stackstate.license.key | b64enc | quote }}
  {{- if .Values.stackstate.receiver.apiKey }}
  sts-receiver-api-key: {{ .Values.stackstate.receiver.apiKey | b64enc | quote }}
  {{- else }}
  sts-receiver-api-key: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.extraEnv.secret }}
    {{- range $key, $value := .Values.extraEnv.secret  }}
  {{ $key }}: {{ $value | b64enc | quote }}
    {{- end }}
  {{- end -}}
