apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackstate-standalone.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-standalone.labels" . | indent 4 }}
type: Opaque
data:
  sts-license-key: {{ .Values.stackstate.license.key | b64enc | quote }}
  sts-receiver-api-key: {{ .Values.stackstate.receiver.apiKey | b64enc | quote }}
