annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2.6.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    # This version is pinned due to https://github.com/bitnami/charts/issues/5032
    version: 1.1.1
  - condition: zookeeper.enabled
    name: zookeeper
    repository: https://charts.bitnami.com/bitnami
    # This version is pinned due to https://github.com/bitnami/charts/issues/5032
    version: 6.0.0
description: Apache Kafka is a distributed streaming platform.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/kafka
icon: https://bitnami.com/assets/stacks/kafka/img/kafka-stack-110x117.png
keywords:
  - kafka
  - zookeeper
  - streaming
  - producer
  - consumer
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: kafka
sources:
  - https://github.com/bitnami/bitnami-docker-kafka
  - https://kafka.apache.org/
version: 12.2.5-stackstate.2
