apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "aws-pod-identity-webhook.fullname" . }}
  labels:
{{ include "aws-pod-identity-webhook.labels" . | indent 4 }}
webhooks:
- name: pod-identity-webhook.amazonaws.com
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  clientConfig:
    service:
      name: {{ include "aws-pod-identity-webhook.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: "/mutate"
    caBundle: {{ .Values.caBundle | quote }}
  sideEffects: None
  admissionReviewVersions: ["v1beta1"]
  rules:
  - operations: [ "CREATE" ]
    apiGroups: ["*"]
    apiVersions: ["v1"]
    resources: ["pods"]
