extraEnv:
  open:
    SOME_KEY: some-value
  secret:
    SOME_SECRET_KEY: some-secret-value
gitlab:
  app: stac-0000
  env: test
image:
  pullPolicy: Always
  repository: 508573134510.dkr.ecr.eu-west-1.amazonaws.com/stackstate
  tag: master
ingress:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: some-test-url.stackstate.io
    kubernetes.io/ingress.class: ingress-nginx-external
    nginx.ingress.kubernetes.io/ingress.class: ingress-nginx-external
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  enabled: true
  hosts:
    - host: some-test-url.stackstate.io
  tls:
    - secretName: star-stackstate-io-tls
      hosts:
        - some-test-url.stackstate.io
persistence:
  enabled: false
  size: 20Gi
  storageClass: gp2
resources:
  limits:
    cpu: "3"
    memory: 8Gi
  requests:
    cpu: "2"
    memory: 4Gi
stackstate:
  demoData:
    enabled: true
  license:
    key: 00000-00000-00000
  receiver:
    baseUrl: https://some-test-url.stackstate.io
