{{- if .Values.rules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: stackstate-processing-pipeline-alerts
  labels:
    app: kube-prometheus-stack
{{- with .Values.rules.additionalLabels }}
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  groups:
    - name: stackstate-processing-pipeline-alerts
      rules:
        - alert: StackStateSyncLatency
          annotations:
            message: The synchronization for \{\{ $labels.namespace }} and integration \{\{ $labels.integration_type }} has high latency \{\{ $value | humanizeDuration }}.
          expr: |
            stackstate_sync_sts_latency_seconds{quantile="0.99", namespace=~{{ .Values.rules.namespaceRegex | quote }}} > 30.000000
          for: 5m
          labels:
            severity: warning
        - alert: StackStateSyncMessageDuration
          annotations:
            message: The synchronization for \{\{ $labels.namespace }} and integration \{\{ $labels.integration_type }} is running very slow, processing time for 1 message is now \{\{ $value | humanizeDuration }}.
          expr: |
            (sum by (integration_type,pod)(rate(stackstate_sync_duration_seconds_sum{namespace=~{{ .Values.rules.namespaceRegex | quote }}}[1m]))
              /
            (sum by (integration_type, pod)(rate(stackstate_sync_changes_total{namespace=~{{ .Values.rules.namespaceRegex | quote }}}[1m])) > 0)) > 5.000000
          for: 5m
          labels:
            severity: warning
{{- end }}
