apiVersion: v2
appVersion: 0.0.0
version: 1.0.0
description: Helm chart for deploying a pull-secret for StackState
home: https://github.com/StackVista/stackstate
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: Jeroen van Erp
    email: jvanerp@stackstate.com
  - name: Remco Beckers
    email: rbeckers@stackstate.com
  - name: Vincent Partington
    email: vpartington@stackstate.com
name: pull-secret
