apiVersion: v1
appVersion: 1.2.6
version: 0.1.14
description: Helm chart for StackState HBase -- includes Zookeeper, and Hadoop for persistent storage.
keywords:
- aiops
- monitoring
- stackstate
- hbase
- hadoop
home: https://gitlab.com/stackvista/devops/helm-charts.git
sources:
- https://github.com/apache/hadoop
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
- name: sc250024
  email: scrooks@stackstate.com
name: hbase
