dependencies:
- name: common
  version: 0.4.4
  repository: https://helm.stackstate.io/
- name: zookeeper
  version: 5.3.4
  repository: https://charts.bitnami.com/bitnami
  condition: zookeeper.enabled
