apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "iceman.fullname" . }}
  labels:
    {{ include "iceman.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - get
    - list
    - watch
