apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iceman.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "iceman.labels" . | indent 4 }}
type: Opaque
data:
  iceman-stackstate-password: {{ required "An entry for .Values.iceman.stackstatePassword is required!" .Values.iceman.stackstatePassword | b64enc | quote }}
  iceman-stackstate-username: {{ required "An entry for .Values.iceman.stackstateUsername is required!" .Values.iceman.stackstateUsername | b64enc | quote }}
  {{- if .Values.extraEnv.secret }}
    {{- range $key, $value := .Values.extraEnv.secret  }}
  {{ $key }}: {{ $value | b64enc | quote }}
    {{- end }}
  {{- end -}}
