apiVersion: v1
kind: ServiceAccount
metadata:
{{- with .Values.rbac.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  name: {{ template "iceman.fullname" . }}
  labels:
    {{- include "iceman.labels" . | nindent 4 }}
