{{- define "common.configmap" -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
apiVersion: {{ .Values.configmap.apiVersion }}
kind: ConfigMap
metadata:
  annotations:
    {{- include "common.annotations.gitlab" . | nindent 4 }}
  {{- with .Values.configmap.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ template "common.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
{{- if .Values.extraEnv.open }}
  {{- range $key, $value := .Values.extraEnv.open  }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
{{- end -}}
{{- end -}}
