{{- define "common.persistentvolumeclaim" -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
apiVersion: {{ .Values.persistentvolumeclaim.apiVersion }}
kind: PersistentVolumeClaim
metadata:
  annotations:
    {{- include "common.annotations.gitlab" . | nindent 4 }}
  {{- with .Values.persistentvolumeclaim.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ template "common.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- include "common.labels.custom" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistentvolumeclaim.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistentvolumeclaim.size | quote }}
{{- if .Values.persistentvolumeclaim.storageClass }}
  {{- if (eq "-" .Values.persistentvolumeclaim.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistentvolumeclaim.storageClass | quote }}
  {{- end }}
{{- end }}
{{- end -}}
{{- end -}}
