{{/*
Common pull secret template
{{ template "common.pull.secret" (dict "username" .Values.image.pullSecretUsername "password" .Values.image.pullSecretPassword "registry" .Values.image.registry "context" $) }}
*/}}
{{- define "common.pull.secret" -}}
  {{- $registryAuthDocument := dict -}}
  {{- $_ := set $registryAuthDocument "username" .username }}
  {{- $_ := set $registryAuthDocument "password" .password }}
  {{- $authMessage := printf "%s:%s" $registryAuthDocument.username $registryAuthDocument.password | b64enc }}
  {{- $_ := set $registryAuthDocument "auth" $authMessage }}
  {{- $registryAuthMap := dict .registry $registryAuthDocument }}
  {{- $dockerAuthsDocuments := dict "auths" $registryAuthMap }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.fullname.short" .context }}-pull-secret
data:
  .dockerconfigjson: {{ $dockerAuthsDocuments | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}
