apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-agent.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cluster-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: agent
spec:
  ports:
  - name: traceport
    port: 8126
    protocol: TCP
    targetPort: 8126
  selector:
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "cluster-agent.name" . }}
