apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-agent.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cluster-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: agent
