apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "cluster-agent.fullname" . }}-clusterchecks
value: {{ .Values.clusterChecks.priorityClassValue }}
globalDefault: false
description: "Priority class for clusterchecks pods"
