{{- if .Values.clusterAgent.config.override }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-agent.fullname" . }}
  labels:
{{ include "cluster-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: cluster-agent
data:
{{- range .Values.clusterAgent.config.override }}
  {{ .path | replace "/" "_"}}_{{ .name }}: |
{{ .data | indent 4 -}}
{{- end -}}
{{- end -}}
