{{- if or .Values.clusterAgent.config.override (and .Values.clusterChecks.enabled .Values.dependencies.kubeStateMetrics.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-agent.fullname" . }}
  labels:
{{ include "cluster-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: cluster-agent
data:
{{- if (and .Values.clusterChecks.enabled .Values.dependencies.kubeStateMetrics.enabled) }}
  _etc_stackstate-agent_conf.d_kubernetes_state.d_conf.yaml: |
    cluster_check: true
    init_config:
    instances:
  {{- if .Values.dependencies.kubeStateMetrics.enabled }}
      - kube_state_url: {{ .Values.clusterChecks.kubeStateMetrics.url | default (printf "http://%s-kube-state-metrics.%s.svc.cluster.local:8080/metrics" .Release.Name .Release.Namespace) }}
        kube_state_token: {{ .Values.clusterChecks.kubeStateMetrics.token }}
  {{- else }}
      - kube_state_url: {{ .Values.clusterChecks.kubeStateMetrics.url | required "If the kubeStateMetrics dependent chart is not enabled, the clusterChecks.kubeStateMetrics.url needs to be configured." }}
  {{- end }}
{{- end }}
{{- range .Values.clusterAgent.config.override }}
  {{ .path | replace "/" "_"}}_{{ .name }}: |
{{ .data | indent 4 -}}
{{- end -}}
{{- end -}}
