{{- $kubeRes := .Values.clusterAgent.collection.kubernetesResources }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-agent.fullname" . }}
  labels:
{{ include "cluster-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: cluster-agent
rules:
{{- if or $kubeRes.namespaces $kubeRes.componentstatuses $kubeRes.configmaps $kubeRes.endpoints $kubeRes.events
    $kubeRes.nodes $kubeRes.persistentvolumeclaims $kubeRes.persistentvolumes $kubeRes.pods $kubeRes.services $kubeRes.secrets }}
- apiGroups:
  - ""
  resources:
  {{- if $kubeRes.namespaces }}
  - namespaces
  {{- end }}
  {{- if $kubeRes.componentstatuses }}
  - componentstatuses
  {{- end }}
  {{- if $kubeRes.configmaps }}
  - configmaps
  {{- end }}
  {{- if $kubeRes.endpoints }}
  - endpoints
  {{- end }}
  {{- if $kubeRes.events }}
  - events
  {{- end }}
  {{- if $kubeRes.nodes }}
  - nodes
  {{- end }}
  {{- if $kubeRes.persistentvolumeclaims }}
  - persistentvolumeclaims
  {{- end }}
  {{- if $kubeRes.persistentvolumes }}
  - persistentvolumes
  {{- end }}
  {{- if $kubeRes.pods }}
  - pods
  {{- end }}
  {{- if $kubeRes.services }}
  - services
  {{- end }}
  {{- if $kubeRes.secrets }}
  - secrets
  {{- end }}
  verbs:
  - get
  - list
  - watch
{{- end }}
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - patch
  - update
{{- if $kubeRes.volumeattachments }}
- apiGroups:
  - "storage.k8s.io"
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
{{- end}}
{{- if or $kubeRes.daemonsets $kubeRes.deployments $kubeRes.replicasets $kubeRes.statefulsets }}
- apiGroups:
  - "apps"
  resources:
  {{- if $kubeRes.daemonsets }}
  - daemonsets
  {{- end }}
  {{- if $kubeRes.deployments }}
  - deployments
  {{- end }}
  {{- if $kubeRes.replicasets }}
  - replicasets
  {{- end }}
  {{- if $kubeRes.statefulsets }}
  - statefulsets
  {{- end }}
  verbs:
  - get
  - list
  - watch
{{- end}}
{{- if $kubeRes.ingresses }}
- apiGroups:
  - "extensions"
  resources:
  {{- if $kubeRes.ingresses }}
  - ingresses
  {{- end }}
  verbs:
  - get
  - list
  - watch
{{- end}}
{{- if or $kubeRes.ingresses $kubeRes.jobs }}
- apiGroups:
  - "batch"
  resources:
  {{- if $kubeRes.cronjobs }}
  - cronjobs
  {{- end }}
  {{- if $kubeRes.jobs }}
  - jobs
  {{- end }}
  verbs:
  - get
  - list
  - watch
{{- end}}
- nonResourceURLs:
  - "/healthz"
  - "/version"
  verbs:
  - get
