apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-agent.fullname" . }}
  labels:
{{ include "cluster-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: cluster-agent
spec:
  replicas: {{ .Values.clusterAgent.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: cluster-agent
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "cluster-agent.name" . }}
{{- with .Values.clusterAgent.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
{{- end }}
  template:
    metadata:
      annotations:
        ad.stackstate.com/stackstate-cluster-agent.check_names: '["openmetrics"]'
        ad.stackstate.com/stackstate-cluster-agent.init_configs: '[{}]'
        ad.stackstate.com/stackstate-cluster-agent.instances: '[{"prometheus_url": "http://%%host%%:5000/metrics","namespace": "stackstate.cluster_agent","metrics": ["go_goroutines","go_memstats_*","process_*","api_requests","stackstate_requests","external_metrics", "cluster_checks_*"]}]'
        {{- include "cluster-agent.checksum-configs" . | nindent 8 }}
        {{- include "cluster-agent.configmap.override.checksum" . | nindent 8 }}
      labels:
        app.kubernetes.io/component: cluster-agent
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "cluster-agent.name" . }}
    spec:
      {{- include "cluster-agent.image.pullSecret.name" (dict "images" (list .Values.clusterAgent.image) "context" $) | nindent 6 }}
      {{- if .Values.clusterAgent.priorityClassName }}
      priorityClassName: {{ .Values.clusterAgent.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ include "cluster-agent.fullname" . }}
      containers:
        - name: cluster-agent
          image: "{{ include "cluster-agent.imageRegistry" . }}/{{ .Values.clusterAgent.image.repository }}:{{ .Values.clusterAgent.image.tag }}"
          imagePullPolicy: "{{ .Values.clusterAgent.image.pullPolicy }}"
          env:
          - name: STS_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "cluster-agent.fullname" . }}
                key: sts-api-key
          - name: STS_CLUSTER_AGENT_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "cluster-agent.fullname" . }}
                key: sts-cluster-auth-token
          - name: LOG_LEVEL
            value: {{ .Values.clusterAgent.logLevel | quote }}
          {{- if .Values.clusterChecks.enabled }}
          - name: STS_CLUSTER_CHECKS_ENABLED
            value: "true"
          - name: STS_EXTRA_CONFIG_PROVIDERS
            value: "kube_endpoints kube_services"
          - name: STS_EXTRA_LISTENERS
            value: "kube_endpoints kube_services"
          {{- end }}
          - name: STS_CLUSTER_NAME
            value: {{.Values.stackstate.cluster.name | quote }}
          - name: STS_COLLECT_KUBERNETES_EVENTS
            value: {{ .Values.clusterAgent.collection.kubernetesEvents | quote }}
          - name: STS_COLLECT_KUBERNETES_METRICS
            value: {{ .Values.clusterAgent.collection.kubernetesMetrics | quote }}
          - name: STS_COLLECT_KUBERNETES_TIMEOUT
            value: {{ .Values.clusterAgent.collection.kubernetesTimeout | quote }}
          - name: STS_COLLECT_KUBERNETES_TOPOLOGY
            value: {{ .Values.clusterAgent.collection.kubernetesTopology | quote }}
          - name: STS_LEADER_ELECTION
            value: "true"
          - name: STS_LOG_LEVEL
            value: {{ .Values.clusterAgent.logLevel | quote }}
          - name: STS_STS_URL
            value: {{ include "cluster-agent.stackstate.url" . }}
          {{- if .Values.clusterAgent.config.configMap.maxDataSize }}
          - name: STS_CONFIGMAP_MAX_DATASIZE
            value: {{ .Values.clusterAgent.config.configMap.maxDataSize | quote }}
          {{- end}}
          {{- range $key, $value := .Values.global.extraEnv.open }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $value := .Values.global.extraEnv.secret }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ include "cluster-agent.fullname" . }}
                key: {{ $key }}
          {{- end }}
        {{- with .Values.clusterAgent.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          volumeMounts:
          - name: logs
            mountPath: /var/log/stackstate-agent
          {{- if .Values.clusterAgent.config.override }}
          {{- range .Values.clusterAgent.config.override }}
          - name: config-override-volume
            mountPath: {{ .path }}/{{ .name }}
            subPath: {{ .path | replace "/" "_"}}_{{ .name }}
          {{- end }}
          {{- end }}
          {{- if and .Values.clusterChecks.enabled .Values.dependencies.kubeStateMetrics.enabled }}
          - name: config-override-volume
            mountPath: /etc/stackstate-agent/conf.d/kubernetes_state.d/conf.yaml
            subPath: _etc_stackstate-agent_conf.d_kubernetes_state.d_conf.yaml
          {{- end }}
    {{- with .Values.clusterAgent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.clusterAgent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.clusterAgent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: logs
          emptyDir: {}
        {{- if or .Values.clusterAgent.config.override  (and .Values.clusterChecks.enabled .Values.dependencies.kubeStateMetrics.enabled) }}
        - name: config-override-volume
          configMap:
            name: {{ include "cluster-agent.fullname" . }}
        {{- end }}
