{{- if .Values.runners.serviceAccountCreate -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- range $key, $value := .Values.runners.serviceAccountAnnotations }}
    {{   $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ include "gitlab-runner.fullname" . }}-executor
  labels:
    app: {{ include "gitlab-runner.fullname" . }}
    chart: {{ include "gitlab-runner.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end -}}
