apiVersion: v2
appVersion: 4.2.1
version: 4.2.1
description: Helm chart for StackState
keywords:
  - aiops
  - monitoring
  - stackstate
home: https://gitlab.com/stackvista/stackstate.git
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: Jeroen van Erp
    email: jvanerp@stackstate.com
  - name: Remco Beckers
    email: rbeckers@stackstate.com
  - name: Vincent Partington
    email: vpartington@stackstate.com
name: stackstate
dependencies:
  - name: common
    repository: https://helm.stackstate.io
    version: 0.4.13
  - name: elasticsearch
    condition: elasticsearch.enabled
    repository: https://helm.stackstate.io
    version: 7.6.2-stackstate.10
  - name: hbase
    condition: hbase.enabled
    repository: https://helm.stackstate.io
    version: 0.1.62
  - name: kafka
    condition: kafka.enabled
    repository: https://helm.stackstate.io
    version: 12.2.5-stackstate.0
  - name: zookeeper
    version: 5.16.0
    repository: https://charts.bitnami.com/bitnami
    condition: zookeeper.enabled
  - name: anomaly-detection
    version: 4.1.23
    repository: https://helm.stackstate.io
    condition: anomaly-detection.enabled
  - name: cluster-agent
    version: 0.4.11
    repository: https://helm.stackstate.io
    condition: cluster-agent.enabled
