dependencies:
- name: common
  repository: https://helm.stackstate.io
  version: 0.4.8
- name: elasticsearch
  condition: elasticsearch.enabled
  repository: https://helm.stackstate.io
  version: 7.6.2-stackstate.4
- name: hbase
  condition: hbase.enabled
  repository: https://helm.stackstate.io
  version: 0.1.40
- name: kafka
  condition: kafka.enabled
  repository: https://charts.bitnami.com/bitnami
  version: 11.7.0
- name: zookeeper
  version: 5.16.0
  repository: https://charts.bitnami.com/bitnami
  condition: zookeeper.enabled
- name: anomaly-detection
  version: 4.1.7
  repository: https://helm.stackstate.io
  condition: anomaly-detection.enabled
- name: cluster-agent
  version: 0.4.2
  repository: https://helm.stackstate.io
  condition: cluster-agent.enabled
