apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws-amicleaner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "aws-amicleaner.labels" . | indent 4 }}
data:
  config: {{ .Values.aws.configFile | b64enc }}
  {{- if .Values.aws.credentialsFile }}
  credentials: {{ .Values.aws.credentialsFile | b64enc }}
  {{- end }}
