{{- define "trafficmirror.deployment.container" -}}
env:
{{- if .Values.trafficmirror.mainUrl }}
- name: MAIN
  value: {{ .Values.trafficmirror.mainUrl | quote }}
{{- end }}
- name: USERNAME
  valueFrom:
    secretKeyRef:
      name: {{ template "common.fullname" . }}
      key: username
- name: PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ template "common.fullname" . }}
      key: password
livenessProbe:
  tcpSocket:
    port: app
readinessProbe:
  tcpSocket:
    port: app
{{- end -}}

{{- define "trafficmirror.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ template "common.container" (list . "trafficmirror.deployment.container") }}
{{- end -}}

{{- $commonDeployment := fromYaml (include "common.deployment" .) -}}
{{- $trafficmirrorDeployment := fromYaml (include "trafficmirror.deployment" .) -}}
{{- toYaml (merge $trafficmirrorDeployment $commonDeployment) -}}
