{{- define "trafficmirror.deployment.container" -}}
env:
{{- if .Values.trafficmirror.mainUrl }}
- name: MAIN
  value: {{ .Values.trafficmirror.mainUrl | quote }}
{{- end }}
- name: USERNAME
  valueFrom:
    secretKeyRef:
      name: {{ template "common.fullname" . }}
      key: username
- name: PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ template "common.fullname" . }}
      key: password
ports:
- containerPort: 8080
  name: app
livenessProbe:
  tcpSocket:
    port: app
readinessProbe:
  tcpSocket:
    port: app
{{- end -}}

{{- define "trafficmirror.deployment" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "trafficmirror.deployment.container" .) -}}
{{- $trafficmirrorContainer := (merge $overrideContainer $commonContainer) }}
spec:
  template:
    spec:
      containers:
      - {{ toYaml $trafficmirrorContainer | nindent 8 }}
{{- end -}}

{{- $commonDeployment := fromYaml (include "common.deployment" .) -}}
{{- $trafficmirrorDeployment := fromYaml (include "trafficmirror.deployment" .) -}}
{{- toYaml (merge $trafficmirrorDeployment $commonDeployment) -}}
