apiVersion: v1
appVersion: 0.1.0
description: Common chartbuilding components and helpers
home: https://gitlab.com/stackvista/devops/helm-charts.git
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
keywords:
  - common
  - stackstate
maintainers:
- name: sc250024
  email: scrooks@stackstate.com
name: common
version: 0.4.2
