apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackstate-steward.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-steward.labels" . | indent 4 }}
type: Opaque
data:
  steward-gitlab-api-token: {{ .Values.steward.gitlab.apiToken | b64enc | quote }}
  {{- if .Values.extraEnv.secret }}
    {{- range $key, $value := .Values.extraEnv.secret  }}
  {{ $key }}: {{ $value | b64enc | quote }}
    {{- end }}
  {{- end -}}
