apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackstate-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-agent.labels" . | indent 4 }}
type: Opaque
data:
  sts-api-key: {{ .Values.stackstate.apiKey | b64enc | quote }}
