---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.fullname.short" . }}
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.fullname.short" . }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "common.fullname.short" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "common.fullname.short" . }}
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "common.fullname.short" . }}
rules:
- apiGroups: ["*"]
  resources:
  - "*"
  verbs: ["*"]
