stackstate:
  components:
    all:
      securityContext:
        enabled: false
    kafkaTopicCreate:
      securityContext:
        enabled: false
    ui:
      securityContext:
        enabled: false
  stackpacks:
    installed:
      - name: openshift
        configuration:
          openshift_cluster_name: api-crc-testing
elasticsearch:
  securityContext:
    enabled: false
  sysctlInitContainer:
    enabled: false
kafka:
  podSecurityContext:
    enabled: false
  volumePermissions:
    enabled: false
hbase:
  hdfs:
    scc:
      enabled: true
    securityContext:
      enabled: true
    volumePermissions:
      enabled: true
      securityContext:
        enabled: true
        privileged: false
  hbase:
    securityContext:
      enabled: false
  console:
    securityContext:
      enabled: false
  tephra:
    securityContext:
      enabled: false
zookeeper:
  securityContext:
    enabled: false
cluster-agent:
  agent:
    scc:
      enabled: true
  enabled: true
  stackstate:
    cluster:
      name: api-crc-testing
      authToken: d8cf3cb5418c03152db54c5c7aa96708
  kube-state-metrics:
    podAnnotations:
      ad.stackstate.com/kube-state-metrics.check_names: '["kubernetes_state"]'
      ad.stackstate.com/kube-state-metrics.init_configs: '[{}]'
      ad.stackstate.com/kube-state-metrics.instances: '[{"kube_state_url":"http://%%host%%:%%port%%/metrics","labels_mapper":{"namespace":"kube_namespace","label_deploymentconfig":"oshift_deployment_config","label_deployment":"oshift_deployment"},"label_joins":{"kube_pod_labels":{"label_to_match":"pod","labels_to_get":["label_deployment","label_deploymentconfig"]}}}]'
    securityContext:
      enabled: false
